apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: zbigniew.zolnierowicz@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - dns01:
        cloudflare:
          email: zbigniew.zolnierowicz@gmail.com
          apiTokenSecretRef:
            name: cert-manager-cloudflare
            key: api-token