apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: bazarr
      version: '9.3.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: "ghcr.io/k8s-at-home/bazarr"
      tag: "v0.9.5"
    env:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        existingClaim: "openebs-hostpath-bazarr-config-pvc"
      media:
        enabled: true
        existingClaim: "nfs-media-pvc"
    additionalVolumeMounts:
    - name: "downloads"
      mountPath: "/downloads"
    additionalVolumes:
    - name: "downloads"
      persistentVolumeClaim:
        claimName: "nfs-downloads-pvc"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - host: bazarr.zolnierowi.cz
          paths:
          - path: /
            pathType: Prefix
      additionalIngresses:
        - enabled: true
          nameSuffix: "api"
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
            - host: bazarr.zolnierowi.cz
              paths:
              - path: /api
                pathType: Prefix
    