---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-downloads-pv
  namespace: media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: media
    name: local-downloads-pvc
  local:
    path: /opt/mounts/down
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi