---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-media-pv
  namespace: media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: media
    name: local-media-pvc
  local:
    path: /opt/mounts/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi