---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-media-pv
  namespace: media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: media
    name: local-media-pvc
  local:
    path: /opt/mounts/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tumor3d-t480-zzolnierowicz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi