---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  namespace: media
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: media
    name: nfs-media-pvc
  nfs:
    server: 192.168.0.13
    path: "/mnt/ChainsawMan-4.5TB-JBOD/Media/Videos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti