apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: '8.1.1'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    env:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        existingClaim: "openebs-hostpath-jackett-config-pvc"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: jackett.zolnierowi.cz
            paths:
            - path: /
              pathType: Prefix