---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-hostpath-sonarr-config-pvc
  namespace: media
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi