apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4Dy0JLU3+6qqsADK,iv:M3BKZxZu1A91D047SbKJCaG4zkvnqgk+qkxZBt6mTh4=,tag:TCrg5CaW/HY518RgGhNdgQ==,type:str]
    user: ENC[AES256_GCM,data:tAjuSuLdVcY=,iv:0da/OCVdt6CNT+KNhkENiXaqKCQSGxG3fHRmgL/t3s0=,tag:W1yZn6dOyf8QhvLxWi/sNA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-04T17:58:03Z"
    mac: ENC[AES256_GCM,data:DDnRA67RWW1Xo5g+bhMUBllxBIzserAdiPDhaGMsrr57NryHEPw0rW98uC4+pJt+yo7bIK8ZK8WJP9mZdVsftLrQtR/egxlCutmj71xvVP2G6z2JNcE2L/TNUztFw7X2VNTLEsblkB8tihDa9+dQpgLgvSVzim67PBH6E0TSshg=,iv:z8RJ+g3YE8d4pwEHflxaU+64ORpFVESpMJbhXXEt2DQ=,tag:H1zlOPLgAzAJlV+sW0WlUQ==,type:str]
    pgp:
        - created_at: "2021-04-04T17:58:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0e/jPhnGxxRAQ//b+40FMCqdnGV7WdWgX3ji9S15RZtWNSpYUS5PY7hPTiU
            5cQ0+/szZpjHxtb6iGFuG05bjoB+IZKMPUAXT7YwJUtdnIq/f58pdJ0yU3d/nBYV
            Iag7U+ED9e2GuVLFqOqIGZYX+V1eBfMJPu/3Ynp2OywbfzqrqyvLCjINczoMORyT
            DFNWJnD1qjVASmdOaajPhGULnw436P+wMBtIhTlI3OxXAT1y6kifaGlGS+Sk9CtA
            qkL/csrz0FudQeVI/SxJ99g02jEdtsphfWsbcSCGKWrDKUaKslKHK1jofbxP4Mts
            oL2e032I1/42hnWwo7OZyfYhY5C+Be4FxwJy+s0QEH0YXzJyDhO1b2peNsKjuMMg
            qXGA1xuIA11F42D4u5qjNXHeceUyOgU4BPsGQVbTtq6WIsRKz44SzvV/4MzGfZVN
            LjbmxhCE8R+nYWCtIrTIehu0AyiBOuAaBqtRFi6pxJzftUwm2NGjslnOPAwINmii
            gGmR53ajnkvlMK5VsDeihHaZJAL8EZbz6p8JW7Xc6RqozKpja29y9BXJAMtJIu5j
            t2DJ7dpY9NAU6Ycpi3MUm6Jj+Lw50uX5wlGk2lHEV/dN++3saz603b+STPvpKgGm
            fOmqekQ84qEu7MTSRV1US1lARZUt2p8/GmjXeXOd0EIH1wYTOHRChxMlI3P86tjS
            XgHuFRrR9C5loyVXPbm7Zt3rPWNx/b50VsGdEGWKLMAtkC42jBKvbaqkKblMNnwK
            jbULsJKi1pTPQf3W+Ss4QqQ3qMYqEqNza0OFHPEsoSUgtxbBvtF5Dsh3TdMLstY=
            =d3za
            -----END PGP MESSAGE-----
          fp: 2E15AC9FF37CE42BF90D71A9C7A530DF82FB58F8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
