---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: plex
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: "ghcr.io/k8s-at-home/plex"
      tag: "v1.23.2.4656-85f0adf5b"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: plex.zolnierowi.cz
            paths:
              - path: /
                pathType: Prefix
    env:
      LIBVA_DRIVER_NAME: i965
    timezone: "Europe/Warsaw"
    persistence:
      config:
        enabled: true
        existingClaim: "openebs-hostpath-plex-config-pvc"
      transcode:
        enabled: true
        existingClaim: "nfs-transcode-pvc"
      data:
        enabled: true
        existingClaim: "nfs-media-pvc"
    podSecurityContext:
      supplementalGroups:
      - 44
      - 109
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 200m
        memory: 256Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 2048Mi
  interval: 1m0s

