apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: deluge
      version: '4.3.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: linuxserver/deluge
      tag: version-2.0.3-2201906121747ubuntu18.04.1
    env:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        existingClaim: "openebs-hostpath-deluge-config-pvc"
      downloads:
        enabled: true
        existingClaim: "nfs-downloads-pvc"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: torrent.zolnierowi.cz
            paths:
            - path: /
              pathType: Prefix