apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '3.26.0'
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
      interval: 1m
  values:
    extraArgs:
      default-ssl-certificate: zolnierowi-cz-tls